### ISSUE TITLE
Add support for IntStream, LongStream and DoubleStream

### ISSUE THREAD

**Issue by minborg** [speedment/jpa-streamer#44]
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.speedment.jpastreamer.builder.standard.internal.StreamBuilder.mapToInt(StreamBuilder.java:84)
	at com.speedment.jpastreamer.autoclose.standard.internal.AutoClosingStream.mapToInt(AutoClosingStream.java:64)
	at com.speedment.jpastreamer.demo.internal.MapToInt.main(MapToInt.java:20)
```

**Comment by minborg** [comment]
This is a pretty large issue.

**Comment by minborg** [comment]
Here is an example:

```

```
   jpaStreamer.stream(sc)
                .sorted(Film$.length.reversed())
                .limit(15)
                .mapToInt(Film$.filmId)
                .forEach(System.out::println);
```


```
